# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rui < Formula
  desc "Terminal UI for managing home routers (Orange Livebox/Funbox today; Play/Fritz on the roadmap)"
  homepage "https://github.com/j4y-w4lk3r/rui"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/j4y-w4lk3r/rui/releases/download/v0.1.2/rui_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "3f33db01a473b71f86c94622f017e2d0c2b9d765e783eb9aefff1219be191b20"

      define_method(:install) do
        bin.install "rui"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/j4y-w4lk3r/rui/releases/download/v0.1.2/rui_0.1.2_Darwin_arm64.tar.gz"
      sha256 "9581726385fb29bca00deedf05b9e3e5fab417a5fe4132bbcd3ae9e97627a63b"

      define_method(:install) do
        bin.install "rui"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/j4y-w4lk3r/rui/releases/download/v0.1.2/rui_0.1.2_Linux_x86_64.tar.gz"
      sha256 "8074e1465f86001e4bd3e0698b551eacce4d1a6fbbaa1133c6472744dc297e11"
      define_method(:install) do
        bin.install "rui"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/j4y-w4lk3r/rui/releases/download/v0.1.2/rui_0.1.2_Linux_arm64.tar.gz"
      sha256 "247fb5a1f209788945395f00c4706838702ae5d5a05917d82193002478da5a51"
      define_method(:install) do
        bin.install "rui"
      end
    end
  end

  test do
    system "#{bin}/rui", "-h"
  end
end
